# Generated by Django 6.0.7 on 2026-07-11 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_membership_group_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR (converted if original was foreign currency)', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Original amount before FX conversion (null if already INR)', max_digits=12, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='FX rate used for conversion (null if INR)', max_digits=10, null=True)),
                ('date', models.DateField()),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('unequal', 'Unequal'), ('percentage', 'Percentage'), ('shares', 'Shares')], default='equal', max_length=20)),
                ('is_settlement', models.BooleanField(default=False, help_text='True if this was detected as a settlement during import')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_expense',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('anomaly_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='core.group')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_made', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.group')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_settlement',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='1-indexed row in the original CSV')),
                ('raw_data', models.JSONField(help_text='Verbatim row data from CSV')),
                ('problem_type', models.CharField(choices=[('exact_duplicate', 'Exact duplicate expense'), ('precision', 'Non-standard precision amount'), ('name_mismatch', 'Inconsistent payer name'), ('missing_payer', 'Missing paid_by'), ('settlement_as_expense', 'Settlement logged as expense'), ('percentage_sum', 'Percentages not summing to 100%'), ('foreign_currency', 'Foreign currency row'), ('non_member', 'Non-member in split_with'), ('conflicting_amounts', 'Same expense, conflicting amounts'), ('negative_amount', 'Negative amount'), ('bad_date', 'Corrupted/implausible date'), ('missing_currency', 'Missing currency'), ('zero_amount', 'Zero-amount expense'), ('ambiguous_date', 'Ambiguous date format'), ('stale_member', 'Stale member after left_on'), ('split_type_conflict', 'split_type vs split_details conflict'), ('deposit_not_expense', 'Transfer/deposit, not shared cost'), ('other', 'Other')], max_length=30)),
                ('detection_method', models.TextField(help_text='Exact rule/heuristic that flagged this row')),
                ('detected_value', models.TextField(blank=True, default='', help_text='The specific value that triggered the anomaly')),
                ('action_taken', models.TextField(blank=True, default='', help_text='What the importer did (kept, dropped, normalized, blocked, etc.)')),
                ('status', models.CharField(choices=[('auto_resolved', 'Auto-resolved by policy'), ('blocked', 'Blocked — needs human review'), ('manually_resolved', 'Manually resolved by human')], default='blocked', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('linked_expense', models.ForeignKey(blank=True, help_text='The expense created from this row, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_anomalies', to='core.expense')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.importbatch')),
                ('linked_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_anomalies', to='core.settlement')),
            ],
            options={
                'verbose_name_plural': 'Import anomalies',
                'db_table': 'core_import_anomaly',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, help_text="This user's share of the expense in INR", max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='core.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_expense_split',
                'constraints': [models.UniqueConstraint(fields=('expense', 'user'), name='unique_split_per_user_per_expense')],
            },
        ),
    ]
