# Generated by Django 6.0.7 on 2026-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_importbatch_settlement_importanomaly_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_membership_per_group',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'group', 'joined_on'), name='unique_membership_per_group_date'),
        ),
    ]
